# 工作流名称
name: Build iwechat and Push to Docker Hub

# 工作流触发器
on:
  # 1. 当有代码推送到 main 分支时触发
  push:
    branches: [ "main" ]
  # 2. 允许在 GitHub Actions 页面手动触发
  workflow_dispatch:

jobs:
  build-and-push:
    # 使用最新的 Ubuntu 运行环境
    runs-on: ubuntu-latest

    steps:
      # 步骤 1: 检出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 使用 run 命令克隆 iwechat 仓库
      - name: Clone iwechat repository
        run: git clone https://github.com/iwechatcom/iwechat.git iwechat-repo

      # 步骤 3: 使用 run 命令设置 QEMU，用于多架构构建
      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      # 步骤 4: 使用 run 命令设置 Docker Buildx
      - name: Set up Docker Buildx
        run: docker buildx create --use

      # 步骤 5: 登录到 Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 步骤 6: 构建并推送多架构 Docker 镜像到 Docker Hub
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/iwechat:latest \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/iwechat:${{ github.sha }} \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --push \
            ./iwechat-repo
